scan_topic: "scan_rp_filtered" # LiDAR topic for subscribe laser scan msg.
odom_topic: "odom_md" # odometry topic for calculating TTC.

frequency: 30.0

range_reversed: true # identify which LiDAR you use - specific lidar range data is reversed (e.g. rplidar).

obstacle_deg: 3 # should satisfy at least 3 degree range data.

ttc_time: 1.5 # minimum TTC time.
ttc_deg: 3 # should satisfy at least 3 degree range data.

signal_distance: 0.2 # minimum distance for to detect front obstacle in (m).
signal_distance_teb: 0.25 # minimum distance for TEB to detect front obstacle in (m).
signal_release: 0.35 # release distance in (m).

# angle_min: -3.14 # should correspond to the akusense driver launch parameter setting.
# angle_max: 3.14 # should correspond to the akusense driver launch parameter setting.

detecting_deg: 120 # LiDAR detecting degree.
detecting_deg_ttc: 100 # ttc detecting degree.
