<?xml version="1.0" ?>
<robot name="fw_rev_04" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="bodyHeight" value="1.02"/>
  <xacro:property name="bodyLength" value="1.15"/>
  <xacro:property name="bodyWidth" value="0.59"/>
  <xacro:property name="bodyMass" value="7.18"/>
  
  <xacro:include filename="$(find fw_rev_04_description)/urdf/materials.xacro"/>
  <xacro:include filename="$(find fw_rev_04_description)/urdf/_materials.urdf.xacro"/>


  <link name="t265_pose_frame"/>

  <joint name="t265_pose_to_link" type="fixed">
    <parent link="t265_pose_frame"/>
    <child link="t265_link"/>
    <origin xyz="0.357 0.01 0.475" rpy="0 0 0"/> 
  </joint>
<!-- "0.357 0.01 0.475" -->
  <link name="t265_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="package://fw_rev_04_description/meshes/sensors/t265.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="aluminum"/>
    </visual>
  </link>

  <joint name="d400_to_t265_joint" type="fixed">
    <parent link="t265_link"/>
    <child link="d400_link"/>
    <origin xyz="0.008 -0.0115 0.059" rpy="0 0 0"/>
  </joint>

  <link name="d400_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="package://fw_rev_04_description/meshes/sensors/d455.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="aluminum"/>
    </visual>
  </link>  

  <joint name="t265_joint" type="fixed">
    <parent link="t265_link"/>
    <child link="base_link" />
    <origin xyz="-0.357 -0.01 -0.475" rpy="0 0.122173 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://fw_rev_04_description/meshes/bases/ottobockframe_2.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${bodyLength+0.1} ${bodyWidth+0.1} ${bodyHeight}"/>
      </geometry>
      <material name="red"/>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0.1265" rpy="0 0 0"/>
      <mass value="7.18"/>
      <inertia ixx="0.15413605166" ixy="0" ixz="0"
               iyy="0.20223666666" iyz="0"
               izz="0.12469805166" />
    </inertial>
  </link>

  <!-- <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint" />
    <origin xyz="-0.34 0 -0.43" rpy="0 0 0"/>
  </joint>    

  <link name="base_footprint"/> -->

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.27 0 0.175" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0.19 0 0" rpy="0 0 3.14"/>
  </joint>

  <link name="base_scan">
  <visual>
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://fw_rev_04_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="blue"/>
  </visual>
  <collision>
    <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.0315" radius="0.055"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.114" />
    <origin xyz="0 0 0" />
    <inertia ixx="0.001" ixy="0.0" ixz="0.0"
             iyy="0.001" iyz="0.0"
             izz="0.001" />
  </inertial>
  </link>

  <!-- <joint name="scan_joint2" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan_rp_filtered"/>
    <origin xyz="0.135 0 0.22" rpy="0 0 3.14"/>
  </joint>

  <link name="base_scan_rp_filtered">
  <visual>
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://fw_rev_04_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="plastic"/>
  </visual>
  <collision>
    <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.0315" radius="0.055"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.114" />
    <origin xyz="0 0 0" />
    <inertia ixx="0.001" ixy="0.0" ixz="0.0"
             iyy="0.001" iyz="0.0"
             izz="0.001" />
  </inertial>
  </link> -->
<!-- 
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.245 0.055" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://fw_rev_04_description/meshes/wheels/left_tire.stl" scale="0.0035 0.0035 0.0035"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.245 0.055" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://fw_rev_04_description/meshes/wheels/right_tire.stl" scale="0.0035 0.0035 0.0035"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="caster_back_joint_right" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_joint_right"/>
    <origin xyz="-0.45 -0.26 -0.023" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_joint_right">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_joint_left" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_joint_left"/>
    <origin xyz="-0.45 0.26 -0.023" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_joint_left">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link> -->

  <!-- <joint name="d455_with_t265_mount" type="fixed">
    <parent link="base_link"/>
    <child link="d455_with_t265_mount"/>
    <origin xyz="0.163 0 0.173" rpy="0 0 0"/>
  </joint>

  <link name="d455_with_t265_mount">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://fw_rev_04_description/meshes/sensors/mount.stl" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link> -->

  <!-- <joint name="t265_joint" type="fixed">
    <parent link="base_link"/>
    <child link="t265_pose_frame"/>
    <origin xyz="0.115 0 0.381" rpy="0 -0.0872665 0"/>
  </joint> -->

</robot>
